
# To skip builds use [ci ckip] in GIT commit-msg

language: node_js
node_js:
  - lts/*

# See Travis CI guide for Node.js <https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions>
