# git-versioning main: ok-lcars-sdk

- type: application/vnd.org.wtwta.project
  main: ok-lcars-sdk
  id: ok-lcars-sdk
  version: 0.0.4-dev # ok-lcars-sdk
  vendor: dotmpe
  distribution: public
  license: MIT

  repositories:
    github: git@github.com:dotmpe/ok-lcars-sdk.git
    dotmpe.origin: git-repos/ok-lcars-sdk.git
    t460s.25-5-bare: /srv/scm-git-25-5-t460s-mpe/ok-lcars-sdk.git

  urls:
    license-info: https://opensource.org/licenses/MIT

  pd-meta:
    tasks:
      document: TODO.txt
      done: .DONE.txt

  scripts:
    init:
    - git submodule update --init
    - htd package update
    - htd package remotes-reset
    - vc regenerate
    - V_DOC_LIST=package-versioned.list verbosity=7 git-versioning check
    check:
    - V_DOC_LIST=package-versioned.list verbosity=7 git-versioning check
    - htd vcflow summary
    status:
    - 'echo "OK! LCARS SDK: \$(vc status) \$(git describe --always)"'
    - 'echo "LCARS SDK: \$(vc status lib/lcars-sdk) \$(cd lib/lcars-sdk/ && git describe --always)"'
    - htd vcflow summary
    install:
    - npm install
    run: run.sh
    run-dev: run-dev.sh
    # Mirror static pages copy from running sitefile
    mirror:
    - hostname=$(hostname)
    - httrack http://$hostname:7011 -O mirror "+*.$hostname/*"
    - rsync -avzui --delete
        ./mirror/${hostname}_7011/ ../dotmpe.github.io/ok-lcars-sdk
