# git-versioning main: ok-lcars-sdk

- type: application/vnd.org.wtwta.project
  main: ok-lcars-sdk
  id: ok-lcars-sdk
  version: 0.0.2 # ok-lcars-sdk
  vendor: bvberkum
  distribution: public
  license: MIT

  urls:
    license-info: https://opensource.org/licenses/MIT

  pd-meta:
    tasks:
      document: TODO.txt
      done: .DONE.txt

  scripts:
    init:
    - git submodule update --init
    - htd package update
    - vc regenerate
    - V_DOC_LIST=package-versioned.list verbosity=7 git-versioning check
    check:
    - V_DOC_LIST=package-versioned.list verbosity=7 git-versioning check
    - htd vcflow summary
    status:
    - 'echo "OK! LCARS SDK: $(vc status) $(git describe --always)"'
    - 'echo "LCARS SDK: $(vc status lib/lcars-sdk) $(cd lib/lcars-sdk/ && git describe --always)"'
    - htd vcflow summary
    install:
    - npm install
    run: run.sh
    run-dev: run-dev.sh
    # Mirror static pages copy from running sitefile
    mirror:
    - hostname=$(hostname)
    - httrack http://$hostname:7011 -O mirror "+*.$hostname/*"
    - rsync -avzui --delete
        ./mirror/${hostname}_7011/ ../bvberkum.github.io/ok-lcars-sdk
