name: ShellCheck

# Trigger the workflow on push or pull request
on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout repository
         uses: actions/checkout@v2
       - name: Setup environment
         run: sudo -E bash -c set
       - name: "ShellCheck"
         run: |
           for sh in $(git ls-files '*.sh')
           do
             if shellcheck -x -s bash $sh
             then echo "OK $sh"
             else echo "FAILED $sh"; exit 1
             fi
           done
         shell: bash
